language: node_js
node_js:
- node
cache: npm
script: npm run build
before_deploy:
- echo -e "$PRIV_KEY" > ~/.key

deploy:
  provider: pages:git
  edge: true
  deploy_key: ~/.key
  skip_cleanup: true
  local_dir: dist
  on:
    branch: master
